
print("Etude Transition A")
source("etude_transition_A.R")
print("Etude Transition B")
source("etude_transition_B.R")
print("Etude Transition C")
source("etude_transition_C.R")
print("Etude Transition D")
source("etude_transition_D.R")
print("Etude Transition E")
source("etude_transition_E.R")
print("Etude Transition F")
source("etude_transition_F.R")
print("Etude Transition G")
source("etude_transition_G.R")
